### ISSUE TITLE
Generate Password-icon is displayed when password field is hidden

### ISSUE THREAD

**Issue by whisdol** [varjolintu/keepassxc-browser#42] opened 2017-12-12 16:49 UTC
On some sites with a floating/hiding login form, the "generate password"-icon is displayed although the password field is hidden.

## Expected Behavior
The "generate password" icon is visible only when the password field is visible as well.

## Current Behavior
The "generate password" icon is visible even when the password field is hidden.

## Possible Solution
This might depend on the implementation of 

## Steps to Reproduce (for bugs)
Open https://spigen.com to see the floating key-icon:
![image](https://user-images.githubusercontent.com/5374166/33896858-382179d2-df64-11e7-8ec4-fa8a3abbee9d.png)
(It is also - generally - quite pixelated on a high-DPI screen)

## General Info
keepassxc-browser - 0.4.3

Operating system: Windows 10
Browser: Nightly
Proxy used: YES

**Comment by varjolintu** [comment] 2017-12-12 17:07
Thanks for the tip. I'll fix this for the next version.

**Comment by varjolintu** [comment] 2017-12-13 16:48
It's a nasty page. The element is visible but still hidden, and the `hidden` value is false too. Trying to solve this soon.

**Comment by whisdol** [comment] 2017-12-13 17:43
Ah, I was afraid that there are endless nasty possibilities to hide the field with JS (which I wanted to mention in the "possible solution" section before I seemingly forgot about it).

**Comment by whisdol** [comment] 2017-12-20 08:29
I found another site with this issue to test against: https://dvd.netflix.com/Plans?dsrc=DVDWEB_BLURAY_NMHEADER_PLANS
The password field is displayed when clicking "Get started".

**Comment by varjolintu** [comment] 2017-12-21 14:30
With the Netflix site I figured out that the visibility functions are not handling `aria-hidden` attribute at all. I added a support for that so that site already works. Still needs a little tuning though.

**Comment by varjolintu** [comment] 2017-12-28 09:08
Support for aria-hidden is added with release 0.4.5.

**Comment by varjolintu** [comment] 2018-01-05 03:17
The cause is found. The final fix will arrive with 0.4.6.

**Comment by varjolintu** [comment] 2018-01-06 08:16
The issue is fixed with 0.4.7 but I need to revert it. Further testing shows that it breaks some sites so I'll need to figure out a better implementation.

**Closed** 2018-04-10 06:56 UTC
Labels: bug
