### ISSUE TITLE
Unable to connect to KeePassXC fork or Proxy on Windows 10 with Firefox

### ISSUE THREAD

**Issue by whisdol** [varjolintu/keepassxc-browser#19] opened 2017-09-11 15:53 UTC
I'm trying to connect the keepassxc-browser (0.2.9) extension for Firefox (Nightly, 57.0a1 (2017-09-11)) to KeePassXC (2.2.0-browser-rc1, but same behavior with beta 8), but nothing happens when clicking the "Connect" button in the extension settings.
I have cloned this repository, edited the path in the -firefox-win.json to point to my KeePassXC-installation and ran the install.bat script, but no luck. There is no reaction from KeePassXC, neither when it is running nor when it is stopped. The "Enable KeePassXC browser extension" option is checked.
I also tried the same with your keepassxc-proxy (after fixing the script for my python installation, for which I have created a [pull request](https://github.com/varjolintu/keepassxc-proxy/pull/2)), but that doesn't start either when the button is clicked. When it's running before the "Connect" button is clicked, no messages are displayed in the proxy either.

**Comment by varjolintu** [comment] 2017-09-11 16:06
Have you tried to enable the Native Messaging feature like described in [this](https://github.com/varjolintu/keepassxc-browser/wiki/Connecting-the-database-with-current-beta-build) wiki document?

**Comment by whisdol** [comment] 2017-09-11 16:13
Yes, the feature is enabled. I also disabled and enabled it again multiple times, but there is no change.

**Comment by varjolintu** [comment] 2017-09-12 07:41
I would like to know how you use the browser extension and KeePassXC fork. Here are the next steps:
- First, don't use any proxy, just install (or uninstall first) the browser support from KeePassXC settings. Then open Firefox and KeePassXC should launch also. Does this happen?
- If the KeePassXC launches with Firefox, can you connect then?
- Test if the Connect button in the popup works, if for some reason the button in Settings doesn't
- Debug the browser extension and see what messages are seen

If you are using the keepassxc-proxy it should start when you start Firefox. If you are seeing the Connect-button I guess both KeePassXC and keepassxc-proxy are launched normally.

**Comment by whisdol** [comment] 2017-09-12 08:41
>First, don't use any proxy, just install (or uninstall first) the browser support from KeePassXC settings. Then open Firefox and KeePassXC should launch also. Does this happen?
I manually removed the key and NativeMessagingHosts-folder in the registry, restarted KeePassXC and enabled Firefox suppport again in the settings. This has created the registry key, which points to "C:\Program Files\KeePassXC\com.varjolintu.keepassxc_browser.json". There is no file at this location. In fact, there are no .json-files in this directory at all.
Starting Firefox does not start KeePassXC.

Copying & pasting the com.varjolintu.keepassxc-browser-firefox-win.json-file from this repository to the location of the registry key (and fixing the path) works: KeePassXC now starts when I start Firefox and I was able to connect from the popup. Now it all works as expected, thank you!

Side note: The association request-window was opened in the background after clicking the Connect-button from the popup, so I had to manually select it to proceed.

**Comment by varjolintu** [comment] 2017-09-12 09:03
So the json file was missing? Was the registry path wrong or missing? I'm just asking this in case the host file installer inside KeePassXC has a bug or did you manually edit those.

It's a known bug that activating the window for new connection does not pop the window to the front. I'm not exactly sure how to fix it. Qt has the same problem under macOS.

**Comment by whisdol** [comment] 2017-09-12 09:22
Yes, the com.varjolintu.keepassxc_browser.json-file was missing.
I just reinstalled KeePassXC a couple of times and found the following behavior:
* After the installation, no com.varjolintu.keepassxc_browser.json-file is present.
* When the NativeMessagingHosts-registry folder for Firefox is present, the entry for Firefox is checked in the settings. No amount of checking and unchecking the Firefox-checkbox (and saving/applying) can create the missing .json-file. Also, when unchecking the Firefox option, saving, and reopening the settings dialogue, Firefox is checked again.
* When the NativeMessagingHosts-registry folder for Firefox is NOT present, the entry for Firefox is not checked in the settings. When checking it and saving, the .json-file is created correctly.

**Comment by varjolintu** [comment] 2017-09-12 09:27
Thank you for this. There might be a bug in the HostInstaller class and I'm going to investigate it.

**Comment by varjolintu** [comment] 2017-09-20 07:39
There was a bug found in the manifest file installer. With Windows there's a tiny problem with the .json files because its path is always the same. And because the manifest file has a different content with Firefox I decided to rename Firefox related .json files to com.varjolintu.keepassxc_browser-firefox.json so those files are not colliding with each other.

The issue is now fixed. Because RC2 builds are needing a one more feature I updated the RC1 binaries. So go get a new installer .exe and try it out :)

**Comment by whisdol** [comment] 2017-09-20 10:34
Yes, it now works mostly as expected: When installing KeePassXC and the registry key is not yet present,  no file is created. When enabling the browser support for Firefox in the settings, the file (now named com.varjolintu.keepassxc_browser-firefox.json) is created correctly and it works.
Unchecking Firefox again now also clears the value of the registry key after clicking apply, and rechecking it (and applying) sets it again. However, the json file is not recreated in that case. I don't think this is a big issue, but it might cause problems for users who uninstall KeePassXC completely, delete the KeePassXC folder and then reinstall it again at a later time. Maybe it's generally a good idea to check for the existence/correctness of the JSON files for all enabled browsers when clicking save/apply.

Side note: The json files and registry entries are not removed when executing the KeePassXC-uninstaller.

**Comment by varjolintu** [comment] 2017-09-20 12:11
Thank you. I will check the following behaviour and inspect if there's a way to include the json and registry removal on uninstall.

**Comment by achmetinternet** [comment] 2017-10-14 05:57
I have a similar problem in Chrome. The error message is: Timeout or not connected to KeePassXC

I use rc2 of the KeePass XC fork and 0.3.3 browser extension.

**Comment by varjolintu** [comment] 2017-10-14 06:33
What proxy application are you using? What does the browser's JavaScript console say?

**Comment by achmetinternet** [comment] 2017-10-14 07:58
Sorry, proxy application? And where can I find the console info? Sorry, not
so much an expert at this. Eventually it is conflicting with a previous
install of the non-forked version 2.2.1?

Sami Vänttinen <notifications@github.com> schrieb am Sa., 14. Okt. 2017 um
08:33 Uhr:

**Comment by varjolintu** [comment] 2017-10-14 08:29
With Chrome you can got to chrome://extensions and check the Developer mode checkbox. After that you can open the Inspect views under keepassxc-browser extension and it should show `background page`.

Official release 2.2.1 is not compatible with this. Only forked 2.2.0 release works at this point.

**Comment by achmetinternet** [comment] 2017-10-14 09:07
Opened it but what do you need from it? On the console tab it says this
after I pressed the "reload" button in the extension:

Error 5: Timeout or not connected to KeePassXC
page.js:85 {message: "Could not establish connection. Receiving end does
not exist."}
page.js:69 {message: "Could not establish connection. Receiving end does
not exist."}
keepass.js:761 Error 5: Timeout or not connected to KeePassXC
page.js:69 {message: "Could not establish connection. Receiving end does
not exist."}
keepass.js:761 Error 5: Timeout or not connected to KeePassXC
_generated_background_page.html:1 Error in event handler for
runtime.onMessage: Error: Expected at most 1 argument for query(), got 2
    at Proxy.<anonymous>
(chrome-extension://iopaggbpplllidnfmcghoonnokmjoicf/browser-polyfill.min.js:1:623)
    at Object.apply
(chrome-extension://iopaggbpplllidnfmcghoonnokmjoicf/browser-polyfill.min.js:1:830)
    at Object.page.removePageInformationFromNotExistingTabs
(chrome-extension://iopaggbpplllidnfmcghoonnokmjoicf/background/page.js:104:16)
    at Object.event.invoke
(chrome-extension://iopaggbpplllidnfmcghoonnokmjoicf/background/event.js:42:7)
    at event.onMessage
(chrome-extension://iopaggbpplllidnfmcghoonnokmjoicf/background/event.js:11:9)
    at
chrome-extension://iopaggbpplllidnfmcghoonnokmjoicf/browser-polyfill.min.js:1:1624


Sami Vänttinen <notifications@github.com> schrieb am Sa., 14. Okt. 2017 um
10:29 Uhr:

**Comment by varjolintu** [comment] 2017-10-14 10:06
Thanks for the log. There's multiple issues like this before the RC3 release so I'm working on it.

**Comment by varjolintu** [comment] 2017-10-14 13:01
Please check if the just released RC3 makes things any better.

**Comment by achmetinternet** [comment] 2017-10-14 13:30
Now this upon pressing reload:

Connecting to native messaging host com.varjolintu.keepassxc_browser
keepass.js:703 Failed to connect: Specified native messaging host not found.
keepass.js:761 Error 5: Timeout or not connected to KeePassXC
keepass.js:761 Error 5: Timeout or not connected to KeePassXC

Sami Vänttinen <notifications@github.com> schrieb am Sa., 14. Okt. 2017 um
15:01 Uhr:

**Comment by varjolintu** [comment] 2017-10-14 13:32
Have you the browser support enabled? [Step 2](https://github.com/varjolintu/keepassxc-browser/wiki/Connecting-the-database-with-current-beta-build).

**Comment by achmetinternet** [comment] 2017-10-14 20:13
Yes.

Sami Vänttinen <notifications@github.com> schrieb am Sa., 14. Okt. 2017 um
15:32 Uhr:

**Comment by achmetinternet** [comment] 2017-10-16 23:00
Anything else I can do to help identify the cause?

TW <Wanne_baumoei@web.de> schrieb am Sa., 14. Okt. 2017, 22:12:

**Comment by varjolintu** [comment] 2017-10-17 04:11
Check the installed .json file that it has the correct path provided. The reload message tells you the native messaging host is not found which might be related to the .json path. If you are under Windows check the registry entries also. Paths and JSON file locations can be found [here](https://developer.chrome.com/extensions/nativeMessaging).

**Comment by achmetinternet** [comment] 2017-10-24 19:34
Where would I find the installed .json file? And what is the correct path?

**Comment by varjolintu** [comment] 2017-10-24 19:42
In Windows the .json file should be in the same folder with KeePassXC.exe.

**Comment by achmetinternet** [comment] 2017-10-24 19:46
Found it. Does it matter that it is named with Firefox but I am using Chrome?

com.varjolintu.keepassxc_browser_firefox.json

**Comment by varjolintu** [comment] 2017-10-24 19:52
Yes. Firefox has it's own script file because the content differs from Chromium-based browsers and both kind of scripts can exists at the same time.

**Comment by achmetinternet** [comment] 2017-10-24 19:53
But it seems in the registry (see my last comment) it is named differently from what is in the actual file path. Should I correct the filename in the directory?

**Comment by varjolintu** [comment] 2017-10-24 19:57
Yes you should.

**Comment by achmetinternet** [comment] 2017-10-24 20:20
I just deleted the json file in the directory, then uninstalled the rc4 and reinstalled it and chose only Chrome as supported browser and then clicked Apply but no new json is created. 

I also tried renaming the earlier file to what was showing in the registry but still the reload button gave me the same error which is why I tried deinstalling.

**Comment by varjolintu** [comment] 2017-10-25 04:19
This is really strange. If you have a correct registry path you can always download the .json file from this repository and change the path parameter to "KeePassXC.exe" and try if it works.

There's clearly something odd going on in the script installer class but I haven't had time to look at it.

**Comment by achmetinternet** [comment] 2017-11-03 23:34
I put com.varjolintu.keepassxc-browser-chrome.json into the folder C:\Program Files\KeePassXC\ and changed the registry entry to point at that json. Now I get the following errors:

keepass.js:89 Uncaught (in promise) TypeError: Cannot read property 'onMessage' of null
    at Promise (keepass.js:89)
    at new Promise (<anonymous>)
    at Object.keepass.sendNativeMessage (keepass.js:86)
    at Promise (keepass.js:565)
    at new Promise (<anonymous>)
    at Object.keepass.changePublicKeys (keepass.js:546)
    at setTimeout (event.js:145)
Promise @ keepass.js:89
keepass.sendNativeMessage @ keepass.js:86
Promise @ keepass.js:565
keepass.changePublicKeys @ keepass.js:546
setTimeout @ event.js:145
Promise rejected (async)
Promise @ keepass.js:565
keepass.changePublicKeys @ keepass.js:546
setTimeout @ event.js:145
setTimeout (async)
kpxcEvent.onReconnect @ event.js:143
browser.tabs.get.then @ event.js:70
Promise resolved (async)
kpxcEvent.invoke @ event.js:44
kpxcEvent.onMessage @ event.js:11
(anonymous) @ browser-polyfill.min.js:1
EventImpl.dispatchToListener @ extensions::event_bindings:403
publicClassPrototype.(anonymous function) @ extensions::utils:140
EventImpl.dispatch_ @ extensions::event_bindings:387
EventImpl.dispatch @ extensions::event_bindings:409
publicClassPrototype.(anonymous function) @ extensions::utils:140
messageListener @ extensions::messaging:238
EventImpl.dispatchToListener @ extensions::event_bindings:403
publicClassPrototype.(anonymous function) @ extensions::utils:140
EventImpl.dispatch_ @ extensions::event_bindings:387
EventImpl.dispatch @ extensions::event_bindings:409
publicClassPrototype.(anonymous function) @ extensions::utils:140
dispatchOnMessage @ extensions::messaging:390
_generated_background_page.html:1 Uncaught (in promise) false
Promise rejected (async)
setTimeout @ event.js:145
setTimeout (async)
kpxcEvent.onReconnect @ event.js:143
browser.tabs.get.then @ event.js:70
Promise resolved (async)
kpxcEvent.invoke @ event.js:44
kpxcEvent.onMessage @ event.js:11
(anonymous) @ browser-polyfill.min.js:1
EventImpl.dispatchToListener @ extensions::event_bindings:403
publicClassPrototype.(anonymous function) @ extensions::utils:140
EventImpl.dispatch_ @ extensions::event_bindings:387
EventImpl.dispatch @ extensions::event_bindings:409
publicClassPrototype.(anonymous function) @ extensions::utils:140
messageListener @ extensions::messaging:238
EventImpl.dispatchToListener @ extensions::event_bindings:403
publicClassPrototype.(anonymous function) @ extensions::utils:140
EventImpl.dispatch_ @ extensions::event_bindings:387
EventImpl.dispatch @ extensions::event_bindings:409
publicClassPrototype.(anonymous function) @ extensions::utils:140
dispatchOnMessage @ extensions::messaging:390

**Comment by varjolintu** [comment] 2017-11-04 08:34
Fixed with release 0.3.9. It should be available soon at AMO and Chrome Web Store.

**Closed by varjolintu** 2017-11-04 08:34 UTC
Labels: bug

**Comment by achmetinternet** [comment] 2017-11-04 15:42
Just wanted to say that it works on my laptop so it might be something with my desktop setup as well :)

**Comment by varjolintu** [comment] 2017-11-04 16:59
Hope so! :) The fix was pretty easy. I just forgot a timeout in a place there's no need for one.. my bad! But nice find anyway. I missed it totally with my Linux machine but reproduced it instantly on macOS.
