### ISSUE TITLE
Login form detection does not work correctly on injected login page

### ISSUE THREAD

**Issue by whisdol** [varjolintu/keepassxc-browser#43] opened 2017-12-14 15:22 UTC
While looking for other examples for issue #42, I noticed that theverge.com is also behaving weirdly.
The login page there seems to be injected via JS after clicking the login button.

## Expected Behavior
Username and password fields should behave like on all other sites.

## Current Behavior
After clicking the login-button, the username and password fields are not recognized as such. There is no possibility to fill my credentials.
After switching to another tab and back to the theverge.com-tab, my credentials are listed in the KeePassXC Browser Plugin window in the navigation bar. When clicking the entry in the browser plugin, the credentials are filled and my username appears in the normal "username selection field" below the username field:
![image](https://user-images.githubusercontent.com/5374166/33998987-7c60b730-e0e9-11e7-8292-4fd23d901d69.png)

When clicking the username, the login page closes unexpectedly.
When using the tab-button instead, I can see that the password field is also filled correctly.

## Possible Solutions
This is probably very specific to how this login page on theverge.com is implemented.
The login page probably closes because the username-selection field is detected as "outside" of the login form. As a user, I feel compelled to click on my username again because the selection field hides the password field and I do not see that the password is already filled as well. Maybe the username selection field does not need to be shown when the credentials are filled from the extension-window.

## Steps to Reproduce (for bugs)
1. Create a password entry for https://www.theverge.com
2. Open theverge.com
3. Click the useraccount-icon or the "Log In" button
4. Notice that the username/password fields are not recognized
5. Switch to another tab and back again
6. Click the KeePassXC-browser-icon and choose the credential to fill the login form
7. Click the username below the username field (see screenshot above).

## General Info
keepassxc-browser - 0.4.3

Operating system: Windows 10
Browser: Nightly
Proxy used: YES

**Comment by varjolintu** [comment] 2017-12-17 06:52
Does your password entry has a `https://auth.voxmedia.com/login?return_to=https%3A%2F%2Fwww.theverge.com%2F` in the URL section? With that everything works for me.

Also, I suggest to try if the same happens with stable browser release.

**Comment by whisdol** [comment] 2017-12-17 09:31
Hm, I tried it in Firefox (stable) and set the URL you mentioned but it still does not work when first opening the login window, only after switching tabs. When switching back again to the theverge.com tab and clicking in the username field, the username selection box appears as well.
(Just to be clear with the behavior: when clicking the login button, the login form opens as an overlay of theverge.com and the issue occurs. Only when clicking the login button before the page load has completed am I being redirected to auth.voxmedia.com.)

**Comment by varjolintu** [comment] 2017-12-17 09:41
Strange. For me the credentials can be chosen right away. And I cannot reproduce the overlay effect. Login always goes to a new separate login page.

**Comment by whisdol** [comment] 2017-12-19 17:09
I see the same issue on https://www.mydealz.de (click "Anmelden"). Can you reproduce it there?

**Comment by varjolintu** [comment] 2017-12-19 17:15
Nope. The autocomplete works when I click the username field. Also the password generator icon is shown.

**Comment by whisdol** [comment] 2017-12-19 17:25
Do you get the overlay, or are you redirected to https://www.mydealz.de/login ?
![image](https://user-images.githubusercontent.com/5374166/34170078-db12e4a2-e4e9-11e7-931a-f2cf26c1b236.png)
Everything works as expected on https://www.mydealz.de/login.
Any way I can debug this for you?

**Comment by varjolintu** [comment] 2017-12-19 18:03
I get the overlay and everything still works. One way to debug this is to download the sources and add the following like to keepassxc-browser.js at line 1125:
`console.log(fields.length);`

Then load the extension manually to your browser and debug it. It should print the count of detected input fields to the console output. This value should increase when the overlay is visible.

**Comment by whisdol** [comment] 2017-12-19 21:13
Ok, I also added log-statements to cip.init, cip.detectNewActiveFields and inside the divDetect-function and learned the following (for mydealz.de)
- cip.init, cip.detectNewActiveFields and the divDetect-function get executed on the initial page load
- After the initial page load, fields.length is 1
- cip.detectNewActiveFields and the divDetect-function do not get executed again
- Clicking the "Anmelden"-button to create the overlay does not change anything or result in any of those functions being called again
- After switching to another tab and back again (after which the fields are detected correctly), the cip.init-function is executed (but none of the other)

This is in a clean profile without any other addons, Firefox 57.0.2 on Windows 10.

**Comment by varjolintu** [comment] 2017-12-20 07:15
Thanks. I finally know the reason for this. I'm trying a few new things to get this work a little better.

Reason for this is that the checking interval gets cleared because one field is detected. So if you click the login icon too late the fields aren't detected. To prove this I tried to click the icon right after the page has loaded -> credential fields are detected.

**Comment by varjolintu** [comment] 2017-12-22 09:56
This issue could be fixed with constant polling to the redetecting credentials but I don't think that's a good solution. This needs some rethinking.

**Comment by varjolintu** [comment] 2017-12-28 09:08
For now you can use the Redetect credential fields button from the popup. There was a bug with it in version 0.4.4 but it's fixed with 0.4.5.

**Closed** 2018-01-06 08:15 UTC
Labels: bug
